import { InputLanguage, OutputLanguage } from "./language.js";
import { PhoenixResources } from "./phoenix.js";

/**
 * Key type generated by Phoenix adaptation defining one "input" (authoring) language and zero or more "output" languages
 */
export interface PhoenixLanguages {
  input: InputLanguage;
  outputs: OutputLanguage[];
}

/**
 * Adaptation implementations comply with this interface.
 * 
 * Dependency injection via PhoenixResources provides utilities for the adaptation to access without concerning UI code.
 */
export interface PhoenixAdaptation {
  getLanguages: (resources: PhoenixResources) => PhoenixLanguages;
}
